
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: ai-code-mother-backend
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_mother?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # redis
  data:
    redis:
      port: 13854
      host: redis-13854.c294.ap-northeast-1-2.ec2.cloud.redislabs.com
      password: UCB51vDJGhWuhPiiIbsGBurLMiZI5Wuo
      ttl: 3600 #默认缓存过期时间，单位秒  1小时
  profiles:
    active: local


# springdoc-openapi
springdoc:
  group-configs:
    - group: v1
      packages-to-scan: com.yff.aicodemother.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

password:
  SALT: a-very-long-secret-key-at-least-32-bytes!!!

logging:
  level:
    com.yff.aicodemother: DEBUG


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




